### ISSUE TITLE
How to fix the NoSuchElementException

### ISSUE THREAD

**Issue by sophia820** [nus-cs2030/2223-s1#18]
# Summary

How can I fix the exception error problem?

## Description:
This is the error I got. How can I remove it?

Exception in thread "main" java.util.NoSuchElementException
--
  | at java.base/java.util.Scanner.throwFor(Scanner.java:941)
  | at java.base/java.util.Scanner.next(Scanner.java:1598)
  | at java.base/java.util.Scanner.nextDouble(Scanner.java:2569)
  | at Main.main(Main.java:12)

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by XihuaZ** [comment]
Did u reinstate a new scanner class after closing a previous scanner class?

**Comment by XihuaZ** [comment]
I think you might have closed ur scanner class and reopening it again.
So something like the code below will throw that error of yours.

method1() {
    while(i<5) {
        method2()
        ...
    }
}

method2() {
    Scanner sc = new Scanner(System.in);
    ...
    sc.close()
}
This code throws that exception as when u do sc.close(), you close the System.in as well, and reinitiating ur sc class won't open ur System.in input stream. I believe this should be the reason why that error occurred.
To fix problem, make sure u are not iterating the opening and closing of the scanner class.

**Comment by danqiye1** [comment]
Not sure if the above resolved your issue, but if you need additional help, you may show us a snippet of your code around Main.java line 12 as indicated by your stack trace:
``` 
 | at java.base/java.util.Scanner.throwFor(Scanner.java:941)
  | at java.base/java.util.Scanner.next(Scanner.java:1598)
  | at java.base/java.util.Scanner.nextDouble(Scanner.java:2569)
  | at Main.main(Main.java:12)
```

**Comment by danqiye1** [comment]
This issue is stale because it has been open for 30 days with no activity.
