### ISSUE TITLE
Docker Launch Error

### ISSUE THREAD

**Issue by ggwoodenmaster** [nus-cs2030/2223-s1#2]
# Summary
Docker encountered exception error upon being launched

## Description 
I have checked that my Windows laptop fulfills all the prerequisites of using Docker, such as turning on the Virtual setting at BIOS and OS versions. However, I noticed that it might be the problem of installing 'Linux kernel update package' (which Docker prompted me to install upon the first launch). My laptop does not show any successful installations of such distributions in PowerShell by using    `wsl --list` command, even after I manually installed the update package through an exe. file. On another machine, once the update package was installed through the exe. file, Docker can run, and I can see the installed distributions on its PowerShell.

## The full error code message
====
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr:
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\main-merges\src\[github.com](http://github.com/)\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 160
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\main-merges\src\[github.com](http://github.com/)\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\main-merges\src\[github.com](http://github.com/)\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 177
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\main-merges\src\[github.com](http://github.com/)\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\main-merges\src\[github.com](http://github.com/)\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\main-merges\src\[github.com](http://github.com/)\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\main-merges\src\[github.com](http://github.com/)\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__22.MoveNext() in C:\workspaces\main-merges\src\[github.com](http://github.com/)\docker\pinata\win\src\Docker.Engines\Engines.cs:line 108

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/60145315/184799908-9b829300-83d6-49d5-8421-67d77c1fb49a.png)

**Comment by ggwoodenmaster** [comment]
After troubleshooting, this seems like a WSL2 issue. WSL2 wasn't able to start properly due to an issue with Winsock module. The solution to fix this is linked here:

https://github.com/microsoft/WSL/issues/4177

As a result, since docker engine was using WSL2 backend, the docker engine also failed to start. Once WSL2 is fixed, docker engine started normally.

**Comment by danqiye1** [comment]
For students who are on Windows machine, there is an option in the settings of Docker Desktop to turn off WSL2 backend. If you have already installed WSL2 and it is working fine, then it is ok to keep using the WSL2 backend. Otherwise, you may find using the HyperV backend to be easier since you don't have to install WSL2 backend.
